"""add_oauth_fields

Revision ID: 36fac768f724
Revises: f75619aa1cb1
Create Date: 2026-06-10 21:45:28.722351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fac768f724'
down_revision: Union[str, None] = 'f75619aa1cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=2083), nullable=True))
    op.add_column('users', sa.Column('oauth_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider_id'], unique=False)
    op.create_unique_constraint('uq_users_oauth', 'users', ['oauth_provider', 'oauth_provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_oauth', 'users', type_='unique')
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('users', 'oauth_connected_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
