import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** @type {import('next').NextConfig} */
const nextConfig = {
  turbopack: {
    root: path.resolve(__dirname),
  },
  transpilePackages: [
    "mermaid",
    "react-markdown",
    "remark-gfm",
    "remark-parse",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-is",
    "mdast-util-from-markdown",
    "mdast-util-to-markdown",
    "mdast-util-gfm",
    "mdast-util-gfm-table",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-task-list-item",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "micromark",
    "micromark-core-commonmark",
    "micromark-extension-gfm",
    "micromark-extension-gfm-table",
    "micromark-extension-gfm-strikethrough",
    "micromark-extension-gfm-task-list-item",
    "micromark-extension-gfm-autolink-literal",
    "micromark-extension-gfm-footnote",
    "micromark-util-combine-extensions",
    "micromark-util-chunked",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-character",
    "micromark-util-classify-character",
    "micromark-util-symbol",
    "micromark-util-types",
    "decode-named-character-reference",
    "character-entities",
    "ccount",
    "escape-string-regexp",
    "markdown-table",
    "zwitch",
    "comma-separated-tokens",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "property-information",
    "space-separated-tokens",
    "devlop",
    "estree-util-is-identifier-name",
    "html-url-attributes",
  ],
};

export default nextConfig;
